### ISSUE TITLE
thumbnail generation is pretty slow

### ISSUE THREAD

**Issue by Crypto90** [stevezau/plex_generate_vid_previews#11]
Hi

I just setup your script on serveral systems and tried to tweak it to get faster thumbnails generated.
I noticed its pretty slow to generate the thumbnails.

How fast does it run for you? My media is located on a smb share, maybe I have some bottleneck somewhere.

I read, that the ffmpeg fps setting for vf_parameters is pretty slow and a faster equivalent should exist by using the frame select function. I did not figured out yet how to use the frame select instead of fps to get the "thumbnails every 10 seconds" output.

Any ideas to speed this up would be great.

Thanks for the script.

**Comment by Crypto90** [comment]
Maybe something like this?

Select frames with a minimum distance of 10 seconds:
`select='isnan(prev_selected_t)+gte(t-prev_selected_t\,10)'`

https://ffmpeg.org/ffmpeg-filters.html#select_002c-aselect

**Comment by stevezau** [comment]
Hi, the script has run fast for me and others. If you are on a samba share, that might be the issue. Have you looked at your CPU/GPU usage during thumbnail generation vs network traffic to identify the bottleneck?

In regards to the script and FFmpeg. The script follows mostly the same parameters and approach as plex uses. I wanted to keep it as close as possible because I'm unfamiliar with FFmpeg.

If there is an after way, then I'm open to a PR, but as knowledge in adv FFmpeg techniques is limited, I won't be much help validating the approach. Sorry.

**Comment by stevezau** [comment]
Closing as I never heard from back you.
