### ISSUE TITLE
Transcoding not actually performed on GPU, CPU faster.

### ISSUE THREAD

**Issue by irakhlin** [stevezau/plex_generate_vid_previews#27]
Hello there,
I ended up using your script with a few modifications so just wanted to say thank you but also point out it a few things I noticed. 

I was attempting to using the cuda acceleration on my nvidia 3060 and noticed that if I set the GPU processes to say 4, and CPU to 4 I will actually get all 8 using GPU, as the logic in the script will continue to enable hardware transcode if the nvidia-smi utility does not show those processes as active on the card. This had me interested and doing a bit deeper dive but it seems NONE of the processes are actually being performed on the GPU.

Using top i got the full command line ffmpeg that was being spawned and attempted to run it manually and saw the same thing. What i noticed was it was using the standard cpu mjpeg transcoder. Further researched showed that there is currently no support for any nvidia cards to perform mjpeg transcoding on gpu. Additionally even if any part was accelerated, because of the filters used (cuda filters have to be used to perform the resizing,etc on gpu) the frames would need to be copied back and forth (https://ffmpeg.org/ffmpeg-filters.html#toc-scale_005fnpp-1).

I ended up removing the cuda parameter and increased the thread count to “auto” and saw significant speed increases.

**Comment by stevezau** [comment]
Hey, I will take a proper look at this when i get some spare time.

In the meantime, I wanted to confirm i understand
- You are seeing this script use only GPU, not CPU even tho you set CPU to 4 threads?
- You are suggesting this might be because the nvidia-smi is not reporting usage correctly for your card?
- Your last sentence in the 1st paragraph seems to contradict the first few lines? You are saying it actually does not use the GPU but is using the CPU?

re the 2nd paragraph. Not sure I understand. 
- I am not an ffmpeg expert. When I built this script I copied the same parameters that Plex uses. 
- If i can recall correctly, i don't think this script was intended to the GPU for jpeg generation. I think from memory this script will use the GPU to decode and CPU to encode? Altho, I am prob wrong given my limited knowledge of ffmpeg. 

Lastly,
> I ended up removing the cuda parameter and increased the thread count to “auto” and saw significant speed increases.
Hmm, so you are seeing far better performance using CPU alone?

**Comment by stevezau** [comment]
hmm, looks like i can reproduce on my machine.. when i get some time ill dig into what's going on.

**Comment by stevezau** [comment]
@irakhlin doing some more testing.. The above wasn't true. When i run the script i can see it using the nvidia GPU to decode.. The encode of the jpg still happens on the CPU.

Comparing 
```/usr/bin/ffmpeg -loglevel info -skip_frame:v nokey -hwaccel cuda -threads:0 1 -i '/data/test.mkv' -an -sn -dn -q:v 4 -vf fps=fps=0.5:round=up,scale=w=320:h=240:force_original_aspect_ratio=decrease /dev/shm/plex_generate_previews/test/img-%06d.jpg``` 

My average speed is 127x.. I can see the GPU working via nvtop. 

vs (-hwaccel cuda removed)
```/usr/bin/ffmpeg -loglevel info -skip_frame:v nokey  -threads:0 1 -i '/data/test.mkv' -an -sn -dn -q:v 4 -vf fps=fps=0.5:round=up,scale=w=320:h=240:force_original_aspect_ratio=decrease /dev/shm/plex_generate_previews/test/img-%06d.jpg``` 

My average speed is 52x

@irakhlin, let's take the script out of the t-shooting... can you run ffmpeg manually to test if it is actually using the GPU? Paste the output of ffmpeg here.

**Comment by hey101** [comment]
I can say if you are on windows replace
`gpu_ffmpeg = [c for c in gpu.processes if c["command"].lower() == 'ffmpeg']`
with
`gpu_ffmpeg = [c for c in gpu.processes if c["command"].lower() == 'ffmpeg.exe']`

Then gpustat will detect the ffmpeg process. However the initial first queue of all the items will return 0 for running processes since it seems to start them all at the same time. However after starting all threads on GPU it seems to detect it properly and start queuing on both CPU and GPU.
